# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!
service: storyCards

#Custom Configuration variables
custom:
  config: ${file(config.json)}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  profile: personal
  region: us-east-1
  environment:
    TRELLO_API_KEY: ${self:custom.config.trelloApiKey}

functions:
  getStoryCards:
    handler: storyCards.get
    events:
      - http:
          path: storyCards/get
          method: post
          cors: true